In [2]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [3]:
type(digits.data)

numpy.ndarray

In [4]:
len(digits.data)

1797

In [5]:
len(digits.target)

1797

In [9]:
len(digits.images)

1797

In [10]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

In [11]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
clf.predict(digits.data[-1:])

array([8])

In [13]:
import pickle

In [14]:
s = pickle.dump(clf, 'digits.model')

TypeError: file must have a 'write' attribute

In [17]:
iris.data.shape

(150, 4)

In [18]:
import numpy as np
from sklearn import datasets
iris_X, iris_y = datasets.load_iris(return_X_y=True)
np.unique(iris_y)

array([0, 1, 2])

In [19]:
# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]
# Create and fit a nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)

knn.predict(iris_X_test)

iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])